// Code generated by ifacemaker; DO NOT EDIT.

package repositories

import (
	"context"

	"github.com/bbedward/enwind-api/ent"
	repository "github.com/bbedward/enwind-api/internal/repositories"
	user_repo "github.com/bbedward/enwind-api/internal/repositories/user"
)

// RepositoriesInterface ...
type RepositoriesInterface interface {
	// Ent() returns the ent client
	Ent() *ent.Client
	// User returns the User repository
	User() user_repo.UserRepositoryInterface
	WithTx(ctx context.Context, fn func(tx repository.TxInterface) error) error
}
